# 页面内容
title: pppeng的博客
author: pppeng
author_description: 一日不书 百事荒芜
author_img: /img/website.svg
logo_img: img/website.svg

# 顶部菜单
menus:
  home: /
  archive: /archives
  tags: /tags
  categories: /categories

# 目录
toc:
  showListNumber: false
  maxDepth: 6
  minDepth: 1

# 已修改为发布时间和更改时间
copyright:
  enable: true
  style: warning


# 配置资源延迟加载
lazyload:
  enable: true
  loadingImg: data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSc4MDAnIGhlaWdodD0nMjQwJz48cmVjdCB4PScwJyB5PScwJyB3aWR0aD0nODAwJyBoZWlnaHQ9JzI0MCcgZmlsbD0nI2ZhZmFmYScvPjx0ZXh0IHg9JzUwJScgeT0nNTAlJyBzdHlsZT0nZG9taW5hbnQtYmFzZWxpbmU6bWlkZGxlO3RleHQtYW5jaG9yOm1pZGRsZTtmb250LXNpemU6NTNweCcgZmlsbD0nI2I3YjdiNyc+5Zu+54mH5Yqg6L295LitPC90ZXh0Pjwvc3ZnPg==
  
  
# 字数统计
wordcount:
  enable: true

# 资源最小化
minify:
  enable: true
  css: true #需要安装 npm install clean-css --save
  js: true #需要安装 npm install uglify-js --save
  html: true #需要安装 npm install html-minifier --save

# 默认主题颜色
color:
  text-color: "#3c485b"
  text-strong-color: "#2f3d4e"
  text-light-color: "#60656a"
  divider-color: "#e6e8ee"
  title-color: "#475c6e"
  link-color: "#3273dc"
  link-hover-color: "#6596e5"
  info-text-color: "#60656a"
  widget-background-color: "#fff"
  body-background-color: "#f2f5f8"
  border-color: "#e1e4e9"
  code-background-color: "#e9eaf0"

# 全局字体
font:
  font-size: 1.03rem 
  font-family: '-apple-system,BlinkMacSystemFont,Segoe UI,system-ui,Roboto,PingFang SC,Hiragino Sans GB,Source Han Sans SC,Noto Sans CJK SC,Noto Sans SC,WenQuanYi Micro Hei,WenQuanYi Zen Hei,Helvetica Neue,Microsoft YaHei,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol' # global font-family

cdn:
  lozad: /js/lib/lozad.min.js
  md5: /js/lib/md5.min.js
  toc: /js/lib/toc-highlight-scroll.min.js
  hightlightcss: /css/libs/atom-one-light.min.css  # https://highlightjs.org/demo 下载样式
  clipboard: /js/lib/clipboard.min.js