# 页面内容
title: 布偶爱吃猪肉脯的博客
author: pppeng
author_description: 逆境中挣扎，享受快乐
author_img: https://img.songhn.com/img/Y67gdd.png
logo_img: https://img.songhn.com/img/Y67gdd.png

# 顶部菜单
menus:
  home: /
  archive: /archives
  tags: /tags
  categories: /categories

# 目录
toc:
  showListNumber: false
  maxDepth: 6
  minDepth: 1

# 已修改为发布时间和更改时间
copyright:
  enable: true
  style: warning


# 配置资源延迟加载
lazyload:
  enable: true
  loadingImg:

# 字数统计
wordcount:
  enable: true

# 资源最小化
minify:
  enable: true
  css: true #需要安装 npm install clean-css --save
  js: true #需要安装 npm install uglify-js --save
  html: true #需要安装 npm install html-minifier --save

# 默认主题颜色
color:
  text-color: "#3c485b"
  text-strong-color: "#2f3d4e"
  text-light-color: "#60656a"
  divider-color: "#e6e8ee"
  title-color: "#475c6e"
  link-color: "#3273dc"
  link-hover-color: "#6596e5"
  info-text-color: "#60656a"
  widget-background-color: "#fff"
  body-background-color: "#f2f5f8"
  border-color: "#e1e4e9"
  pre-color: "#2d2d2d"
  code-color: "#50687c"
  code-background-color: "#e9eaf0"

# 全局字体
font:
  font-size: 1.03rem 
  font-family: '-apple-system,BlinkMacSystemFont,Segoe UI,system-ui,Roboto,PingFang SC,Hiragino Sans GB,Source Han Sans SC,Noto Sans CJK SC,Noto Sans SC,WenQuanYi Micro Hei,WenQuanYi Zen Hei,Helvetica Neue,Microsoft YaHei,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol' # global font-family

cdn:
  lozad: /js/lib/lozad.min.js
  md5: /js/lib/md5.min.js
  toc: /js/lib/toc-highlight-scroll.min.js