name: Auto Deplay To GitPage

on:
  push:
    branches: [ "main" ]

env:
  GIT_USER: pgaofeng
  GIT_EMAIL: penggaofeng@163.com
  GIT_DEPLOY_REPO: pgaofeng/pgaofeng.github.io
  GIT_DEPLOY_BRANCH: main

jobs:
  build-and-deplay:
    name: Build on node
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.DEPLAY_KEY_PRIVATE}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_DEPLOY_REPO }}
          ref: ${{ env.GIT_DEPLOY_BRANCH }}
          path: .deploy_git
      - name: UpdatePostTime
        run: |
          cd .deploy_git
          sh update-date.sh
          cd ../

      - name: Install dependencies
        run: |
          npm init -f
          npm install -g hexo-cli
          npm install

      - name: Generate Blog
        run: |
          hexo init blog
          mv -f .deploy_git blog/.deploy_git
          rm -rf blog/source
          mv -f source blog/source
          mv -f blog/source/_posts/img blog/source/img
          cp _config.yml blog/_config.yml
          cp -r hexo-theme-kaze blog/themes/
          
      - name: Deploy Blog
        run: |
          cd blog
          npm install hexo-deployer-git --save
          npm install clean-css --save
          npm install uglify-js --save
          npm install html-minifier --save
          hexo g
          mv ../website.md public/README.md
          hexo d
