name: 自动部署

on:
  push:
    branches:
      - main

env:
  GIT_USER: pgaofeng
  GIT_EMAIL: penggaofeng@163.com
  DEPLOY_REPO: pgaofeng/pgaofeng.github.io
  DEPLOY_BRANCH: main
jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.DEPLAY_KEY_PRIVATE}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: Generate Blog
        run: |
          hexo init blog
          rm -rf blog/source/_posts
          mv -d _posts blog/source
          cp _config.yml blog/_config.yml
          cp -r snark blog/theme/

      -name: Deploy Blog
        run: |
          cd blog
          hexo clean
          hexo g
          hexo d
